// Error Handling (Try/Catch/Throw)

function handleErros(erro) {
    //throw new Error('vish!ü§¶üèæ‚Äç')
    //throw 10
    //throw true
    //throw 'msg!'
    throw {
        name: erro.name,
        msg: erro.message,
        date: new Date
    }
}
function  printNameYelled(obj) {
    // alguns c√≥digos tem probabilidade maior de gerar erros, e s√£o nesses casos que usa-se estes comandos.
    try {
        console.log(obj.name.toUpperCase() + '!!');
    } catch (e) {
        handleErros(e)
    }finally {
        console.log('Done')
    }
}

const obj = { name: 'Lazarento'};
printNameYelled(obj);